=== anukat2015/Knora/webapi/src/main/resources/XML-schemas/diplomatic.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="region">
        <xs:complexType mixed="true">
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element name="rendition">
                    <xs:complexType mixed="true">
                        <xs:choice maxOccurs="unbounded" minOccurs="0">
                            <xs:element name="lb"/>
                            <xs:element name="formula" type="formula_element"></xs:element>
                        </xs:choice>
                        <xs:attribute name="type" type="rendition_attribute" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lb"/>
                <xs:element name="formula" type="formula_element"></xs:element>
            </xs:choice>
            <xs:attribute name="id" type="xs:decimal"></xs:attribute>
            <xs:attribute name="regiontype" type="regiontype_attribute" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>



    <!--

    Type definitions to be reused

    -->

    <xs:simpleType name="rendition_attribute">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\s?underline|\s?center|\s?strike|\s?above)+"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="notation_attribute">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TeX"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="regiontype_attribute">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TT"/> <!-- Title Text -->
            <xs:enumeration value="T"/> <!-- Text -->
            <xs:enumeration value="M"/> <!-- Math -->
            <xs:enumeration value="F"/> <!-- Figure -->
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="formula_element" mixed="true">
        <xs:attribute name="notation" type="notation_attribute" use="required"></xs:attribute>
    </xs:complexType>



</xs:schema>

=== anukat2015/Knora/webapi/src/main/resources/XML-transcriptions/Med_151_1_diplomatic.xml
<?xml version="1.0" encoding="UTF-8"?>
<region id="1" regiontype="TT" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XML-schemas/diplomatic.xsd">
    <rendition type="center underline">CLI</rendition>.<lb/><lb/>
    <rendition type="underline">Examen modi Renaldiniani inscribendi q&#780;vis polygona regularia in circulo,<lb/>
        depromti ex Lib. II. de Resol. &#38; Composi: Mathem: p. 367.</rendition> (<rendition type="underline">vid. Sturmii<lb/>
            Mathesin enucleatam p. 38.</rendition>)
</region>

=== anukat2015/Knora/webapi/src/main/resources/XML-transcriptions/Med_151_2_diplomatic.xml
<?xml version="1.0" encoding="UTF-8"?>
<region id="2" regiontype="T" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XML-schemas/diplomatic.xsd">
    Modus hic est: Fiat triang: æquil: <formula notation="TeX">ABD</formula>, divisâq́  diametro <formula notation="TeX">AB</formula> in tot partes æquales,<lb/>
    quot laterum est figura inscribenda, duabusq́ earum p̃termissis <rendition type="strike">et</rendition> à <formula notation="TeX">B</formula> versùs <formula notation="TeX">A</formula>, ducat,<lb/>
    per initium tertiæ recta <formula notation="TeX">DF</formula>, &amp; hinc recta <formula notation="TeX">FB</formula>, quam putat esse latus polygoni optati<lb/><lb/>
    <rendition type="underline">Anal</rendition>: Sit secta diameter utcunq́ in <formula notation="TeX">E</formula>, <formula notation="TeX">e</formula> , ductæq́ <formula notation="TeX">DEF</formula>, <rendition type="above"><formula notation="TeX">FA</formula>,</rendition> &amp; <formula notation="TeX">FB</formula> &amp; demissa in diametrum per-<lb/>
    pendicularis <formula notation="TeX">FG</formula>, fiat <formula notation="TeX">CB=a</formula>, <formula notation="TeX">CE</formula> vel <formula notation="TeX">Ce=b</formula>, <formula notation="TeX">FB=x</formula>, unde <formula notation="TeX">AF=\sqrt{\mathstrut}\,\overline{4aa-xx}</formula><lb/>
    
</region>
