=== anukat2015/Knora/webapi/src/main/resources/XML-schemas/meditatio.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="meditatio">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="1">
                <xs:element name="region" type="region_element"/>
            </xs:choice>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>


    <!--

    Type definitions referred to

    -->

    <!--

        <region id="KnoraIRI" regiontype="TT|T|M|F"> ... </region>

        A region represents a geometrical figure on the mansucript:
        - "id": IRI of the Knora region containing the geometrical information
        - "regiontype": Type of the region (see "regiontype_attribute")

    -->

    <xs:simpleType name="regiontype_attribute">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TT"/> <!-- Title Text -->
            <xs:enumeration value="T"/> <!-- Text -->
            <xs:enumeration value="M"/> <!-- Math -->
            <xs:enumeration value="F"/> <!-- Figure -->
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType mixed="true" name="region_element">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="rendition">
                <xs:complexType mixed="true">
                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                        <xs:element name="lb"/>
                        <xs:element name="formula" type="formula_element"/>
                        <xs:element name="abbr" type="abbr_element"/>
                        <xs:element name="corr" type="corr_element"/>
                        <xs:element name="add" type="add_element"/>
                        <xs:element name="del" type="del_element"/>
                    </xs:choice>
                    <xs:attribute name="type" type="renditiontype_attribute" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="lb"/>
            <xs:element name="formula" type="formula_element"/>
            <xs:element name="abbr" type="abbr_element"/>
            <xs:element name="corr" type="corr_element"/>
            <xs:element name="add" type="add_element"/>
            <xs:element name="del" type="del_element"/>
            <xs:element name="region" type="region_element"/>

        </xs:choice>
        <xs:attribute name="id" type="xs:anyURI" use="required"/>
        <xs:attribute name="regiontype" type="regiontype_attribute" use="required"/>
    </xs:complexType>


    <!--

        <rendition type="(\s?underline|\s?center|\s?strike|\s?above)"> ... </rendition

        Represents layout information:
        - "underline": text underlined in manuscript
        - "center": text centered in manuscript
        - "strike": text struck through in manuscript
        - "above": text positioned above baseline in manuscript

        A type attribute may hold several of these.

    -->

    <xs:simpleType name="renditiontype_attribute">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\s?underline|\s?center|\s?strike|\s?above)+"/>
        </xs:restriction>
    </xs:simpleType>


    <!--

        <formula notation="TeX">AB</formula>

        Represents a mathematical formula:
        - "notation": indicates the format in which the fomula is written

        At the moment, only TeX is supported. It has to be MathJax compliant which means that only the math parts of LaTeX may be used, not the text parts.

    -->

    <xs:simpleType name="notation_attribute">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TeX"/> <!-- formula written in TeX -->
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="formula_element" mixed="true">
        <xs:attribute name="notation" type="notation_attribute" use="required"/>
        <xs:attribute name="repl" type="repl_attribute" use="optional"/>
    </xs:complexType>

    <!--

        <abbr expan="Analysis">Anal.</abbr>

        Expands an abbreviation:
        - "expan": expansion of the abbreviation

    -->

    <xs:simpleType name="expan_attribute">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="abbr_element" mixed="true">
        <xs:attribute name="expan" use="required" type="expan_attribute"/>
    </xs:complexType>


    <!--

        <corr repl="y">x</corr>

        Represents an editorial intervention:
        - "repl": replacement for the original text

    -->

    <xs:simpleType name="repl_attribute">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="corr_element" mixed="true">
        <xs:attribute name="expan" use="required" type="repl_attribute"/>
    </xs:complexType>

    <!--

        <add>added by author</add>

        Represents text that was added to the base text by the author himself.

    -->

    <xs:complexType name="add_element" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="formula" type="formula_element"/>
        </xs:choice>
    </xs:complexType>

    <!--

        <del>deleted by author</del>

        Represents text that was deleted by the auhtor himself.

    -->

    <xs:complexType name="del_element" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="formula" type="formula_element"/>
        </xs:choice>
    </xs:complexType>



</xs:schema>

=== anukat2015/Knora/webapi/src/main/resources/XML-transcriptions/Med_151_diplomatic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE meditatio SYSTEM "../XML-schemas/diplomatic.dtd">
<meditatio id="151" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XML-schemas/meditatio.xsd">
    <region id="1" regiontype="TT">
        <rendition type="center underline">CLI</rendition><corr expan="">.</corr>&line;
        <rendition type="underline">Examen modi Renaldiniani inscribendi &quae;vis polygona regularia in circulo,&line;
            depromti ex Lib. II. de <abbr expan="Resolutione">Resol.</abbr> &amp; <abbr expan="Compositione">Composi:</abbr> <abbr expan="Mathematica">Mathem:</abbr> p. 367.</rendition>
        (<rendition type="underline">vid<corr expan="e">.</corr> Sturmii<lb/>Mathesin enucleatam p. 38.</rendition>)
    </region>

    <region id="2" regiontype="T">
        Modus hic est: Fiat <abbr expan="triangulum">triang:</abbr> <abbr expan="&ae;quilaterum">&ae;quil:</abbr> <formula notation="TeX">ABD</formula>, divis&ahat;&que; diametro <formula notation="TeX">AB</formula> in tot partes &ae;quales,&line;
        quot laterum est figura inscribenda, duabus&que; earum &prae;termissis <rendition type="strike"><del>et</del></rendition> &agrav; <formula notation="TeX">B</formula> vers&ugrav;s <formula notation="TeX">A</formula>, duca&tur;,&line;
        per initium terti&ae; recta <formula notation="TeX">DF</formula>, &amp; hinc recta <formula notation="TeX">FB</formula>, quam putat esse latus polygoni optati<corr expan="."></corr>&line;
        <rendition type="underline"><abbr expan="Analysis">Anal</abbr></rendition>: Sit secta diameter utcun&que; in <formula notation="TeX">E</formula>, <formula notation="TeX">e</formula> , duct&ae;&que;<formula notation="TeX">DEF</formula>, <rendition type="above"><add><formula notation="TeX">FA</formula>,</add></rendition> &amp; <formula notation="TeX">FB</formula> &amp; demissa in diametrum per&hyphen;
        pendicularis <formula notation="TeX">FG</formula>, fiat <formula notation="TeX">CB=a</formula>, <formula notation="TeX">CE</formula> vel <formula notation="TeX">Ce=b</formula>, <formula notation="TeX">FB=x</formula>, unde <formula notation="TeX">AF=\sqrt{\mathstrut}\,\overline{4aa-xx}</formula>&line;
    </region>

    <region id="3" regiontype="F"></region>

    <region id="4" regiontype="M">
        <formula notation="TeX">
            \begin{array}{ccccccc}
            AB &amp; . &amp; BF &amp; :: &amp; BF &amp; . &amp; BG. \\
            2a &amp; . &amp; x &amp; :: &amp; x &amp; . &amp; \dfrac{\mathstrut xx}{2a}
            \end{array}
        </formula>
        hinc
        <formula notation="TeX">
            \begin{array}{lccc}
            &amp; \pm \,GB &amp; \mp \,CB &amp; -\,CE  \\
            \quad GE= &amp; \pm \,\dfrac{\mathstrut xx}{2a} &amp; \mp \,a &amp; -\,b
            \end{array}
        </formula>
    </region>


    <region id="5" regiontype="M">

        <formula notation="TeX" repl="
            \begin{array}{ccccccc}
            BA &amp; . &amp; AF &amp; :: &amp; AF &amp; . &amp; AG \\
            2a &amp; . &amp; \sqrt{4aa-xx} &amp; :: &amp; \sqrt{4aa-xx} &amp; . &amp; \dfrac{4aa-xx}{2a}
            \end{array}
            ">
            \begin{array}{ccccccc}
            BA &amp; . &amp; AF &amp; :: &amp; AF &amp; . &amp; AG  \\
            2a &amp; . &amp; \sqrt{\mathstrut}\,\overline{4aa-xx} &amp; :: &amp; \sqrt{\mathstrut}\,\overline{4aa-xx} &amp; . &amp; \dfrac{4aa-xx}{2a}
            \end{array}
        </formula>

        <formula notation="TeX" repl="
            \begin{array}{cc}
            AG \,\times\, GB &amp; \\
            \dfrac{4aaxx-x^4}{4aa} &amp; =GF\text{q}
            \end{array}
            ">
            \begin{array}{cc}
            AG \,\times\, GB &amp;  \\
            \dfrac{4aaxx-x4}{4aa} &amp; =GF\text{q}
            \end{array}
        </formula>

        <formula notation="TeX" repl="
            \begin{array}{ccccccc}
            GE\text{q} &amp; . &amp; GF\text{q} &amp; :: &amp; CE\text{q} &amp; . &amp; CD\text{q} \quad (DB\text{q}-CB\text{q}) \\
            \dfrac{x^4}{4aa} + aa + bb - xx \mp \dfrac{bxx}{a} \pm 2ab &amp; . &amp; \dfrac{4aaxx-x^4}{4aa} &amp; :: &amp; bb &amp; . &amp; 3aa \quad (4aa - aa)
            \end{array}
            ">
            \begin{array}{ccccccc}
            GE\text{q} &amp; . &amp; GF\text{q} &amp; :: &amp; CE\text{q} &amp; . &amp; CD\text{q} \quad (DB\text{q}-CB\text{q})  \\
            \dfrac{x4}{4aa} + aa + bb - xx \mp \dfrac{bxx}{a} \pm 2ab &amp; . &amp; \dfrac{4aaxx-x4}{4aa} &amp; :: &amp; bb &amp; . &amp; 3aa \quad (4aa - aa)
            \end{array}
        </formula>

    </region>

    <region id="6" regiontype="M">
        unde invenitur
        <formula notation="TeX" repl="x^4 = \frac{12a^4xx \pm 12a^3bxx + 4aabbxx - 12a^6 - 12a^4bb \mp 24a^5b}{3aa + bb}">
            x4 = \frac{12a4xx \pm 12a3bxx + 4aabbxx - 12a6 - 12a4bb \mp 24a5b}{3aa + bb}
        </formula>

    </region>

    <region id="7" regiontype="M">
        <formula notation="TeX" repl="x = \sqrt{2aa\ \frac{\pm 6a^3b \pm 2aab \sqrt{3aa-2bb}}{3aa + bb}}">
            x = \sqrt{\vphantom{\frac{0^0}{0}}}\,\overline{2aa\ \frac{\pm 6a3b \pm 2aab \sqrt{\mathstrut}\,\overline{3aa-2bb}}{3aa + bb}}
        </formula>
    </region>

</meditatio>
